### PR TITLE
Implement upsert_users

### PR DESCRIPTION
**Pull request by abetomo**
@toru-takahashi 

* Add the columns to support
* Implement update_users
    * Add a method to handle job_status

### CODE REVIEW

**Comment by abetomo** [comment]
@toru-takahashi Could you review it?

**Comment by toru-takahashi** [comment]
Sorry, I took a vacation and I overlooked this request.
Let me check it in this week.

**Comment by toru-takahashi** [comment]
NOTE:
- name_column in README is needed to change from long to string.
- email_column in README is needed to change from long to string.

Name = "" is not acceptable in Zendesk API.
```
2020-10-07 10:30:11.647 +0900 [WARN] (embulk-output-executor-0): ID:0, Error:UserCreateError, Details: : Name:  is too short (minimum one character)
```

When a new user is created, the following warning happens. Need to fix logging code to show a proper message.

```
2020-10-07 10:38:37.801 +0900 [WARN] (embulk-output-executor-0): ID:423040099793, Error:, Details:
```

When a role is incorrect, 400 error happens.

```
2020-10-07 10:35:22.039 +0900 [WARN] (embulk-output-executor-0): the server responded with status 400 -- post https://treasuredata1439260692.zendesk.com/api/v2/users/create_or_update_many
```

But, others look good to me.
After merging it, I'll fix README, and then release v0.0.5

**Comment by toru-takahashi** [comment]
Test config:

```
in:
  type: config
  columns:
  - {name: id, type: long}
  - {name: tags, type: json}
  - {name: user_fields, type: json}
  - {name: name, type: string}
  - {name: phone, type: string}
  - {name: email, type: string }
  - {name: external_id, type: long}
  - {name: role, type: long}
  values:
  - - [ 9811482788, ["tag1", "tag2"], { "xxxx": "Support description", "date": "2013-02-27T20:35:55Z" }, 'name testing', '000-000-000', 'toru+3@treasure-data.com', 111, 2859697]
    - [ 0001010, ["tag3"], { "xxxx": "Support description" }, 'name testing2', '000-0000001', 'toru+4@treasure-data.com', 113, 2859707]
out:
  type: zendesk_users
  login_url: https://xxxx.zendesk.com
  auth_method: token
  username: xxxx
  token: xxxxx
  method: upsert
  id_column: id
  tags_column: tags
  user_fields_column: user_fields
  name_column: name
  phone_column: phone
  email_column: email
  external_id_column: external_id
  #role_column: role
```

**Comment by abetomo** [comment]
Thanks for the review.

**Comment by toru-takahashi** [comment]
Released v0.0.5 https://rubygems.org/gems/embulk-output-zendesk_users/versions/0.0.5

**Pull request merged**
